name = "KolmogorovArnold"
uuid = "eec8b66d-f71a-4a43-b228-0fe5d6721cd3"
authors = ["Vedant Puri <vedantpuri@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LuxCore = "bb33d45b-7691-41d6-9220-0943567d0623"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
WeightInitializers = "d49dbf32-c5c2-4618-8acc-27bb2598ef2d"

[compat]
julia = "1.6"

[extras]
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCUDA = "d0bbae9a-e099-4d5b-a835-1c6931763bda"
LuxDeviceUtils = "34f89e08-e1d5-43b4-8944-0b49ac560553"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"

[targets]
test = ["Test", "Lux", "Zygote", "Optimisers", "OptimizationOptimJL"]
